<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Member extends CI_Controller {

    public function __construct() {
        parent::__construct();
        // Load necessary models
        $this->load->helper('url');
        $this->load->model(array('m_member', 'm_user'));

        // Set default timezone
        date_default_timezone_set('Asia/Jakarta');
    }

    public function dataMember() {
        // Check if the user has Admin level, otherwise redirect to login
        if ($this->session->userdata('level') !== 'Admin') {
            redirect('login');
        } else {
            // Fetch admin data and member data
            $data['admin'] = $this->m_user->selectAdmin()->row();
            $data['member'] = $this->m_member->getMember()->result();

            // Load views with data
            $this->load->view('admin/header', $data);
            $this->load->view('admin/dataMember', $data);
            $this->load->view('admin/footer');
        }
    }

    public function import()
{
    $data['admin'] = $this->m_user->selectAdmin()->row(); // Get admin data
    
    // Check if the user is logged in as 'Admin'
    if (!$this->session->userdata('level') == 'Admin') {
        redirect('login'); // Redirect to login if not an Admin
    } else {
        if (isset($_POST['preview'])) { // If the user clicked the 'Preview' button on the form
            // Perform file upload using the upload function in BarangModel.php
            $upload = $this->m_member->upload_file($this->filename);

            if ($upload['result'] == "success") { // If upload is successful
                // Load PHPExcel plugin to read the Excel file
                $excelreader = new PHPExcel_Reader_Excel2007();
                $loadexcel = $excelreader->load('excel/' . $this->filename . '.xlsx'); // Load the uploaded Excel file
                $sheet = $loadexcel->getActiveSheet()->toArray(null, true, true, true); // Get sheet data as an array
                
                // Pass the sheet data to the view for display
                $data['sheet'] = $sheet;
            } else { // If upload fails
                $data['upload_error'] = $upload['error']; // Get error message
                $this->load->view('admin/header', $data);
                $this->load->view('admin/tambahmember');
                $this->load->view('admin/footer');
            }
        }

        // Get the list of members to display
        $data['member'] = $this->m_member->getMember()->result();
        
        // Load views to display the admin panel
        $this->load->view('admin/header', $data);
        $this->load->view('admin/tambahmember');
        $this->load->view('admin/footer');
    }
}

public function tambah()
{
    // Load the Excel reader for .xlsx files
    $excelreader = new PHPExcel_Reader_Excel2007();
    
    // Load the uploaded file from the 'excel' folder
    $loadexcel = $excelreader->load('excel/' . $this->filename . '.xlsx');
    
    // Convert the active sheet data into an array
    $sheet = $loadexcel->getActiveSheet()->toArray(null, true, true, true);
    
    // Create an empty array to store data to be inserted into the database
    $data = [];
    $numrow = 1;

    // Loop through each row of the sheet
    foreach ($sheet as $row) {
        // Skip the first row as it contains column names (headers)
        if ($numrow > 1) {
            // Add each row's data to the $data array
            array_push($data, [
                'idMember' => "", // Empty id, it will be auto-generated by the database
                'nama' => $row['B'], // Name from column B in the Excel file
                'jk' => $row['C'], // Gender from column C
                'alamat' => $row['D'], // Address from column D
            ]);
        }
        $numrow++; // Increment the row counter
    }

    // Insert the data into the database using the model method 'tambah'
    $this->m_member->tambah($data);
    
    // Set a session flash message indicating the success
    $this->session->set_flashdata('info', 'Data berhasil ditambah');
    
    // Redirect to the member data page
    redirect("member/dataMember");
}

}
?>
